# Generated by Django 4.1.6 on 2023-11-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
